-----------------Total no. of Madrasha from IMS module

select count(*) from memis_live.ims_institute

---------------List of Madrasha from IMS module

select ins_name,eiin,address,mobile_no,email,locd.name division,LOCZ.NAME zilla,LOCt.NAME upazilla from memis_live.ims_institute JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID)
                  LEFT JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) --where f_ins_type_id=10


----------------------Total no. of Dakhil Madrasha from IMS module

select count(*) from memis_live.ims_institute where f_ins_type_id=7


-----------------------List of Dakhil Madrasha from IMS module

select ins_name,eiin,address,mobile_no,email,locd.name division,LOCZ.NAME zilla,LOCt.NAME upazilla from memis_live.ims_institute JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID and IMS_INSTITUTE.f_ins_type_id=7)
                  LEFT JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) --where f_ins_type_id=10


----------------------Total no. of Alim Madrasha from IMS module

select count(*) from memis_live.ims_institute where f_ins_type_id=8


------------------------List of Alim Madrasha from IMS module

select ins_name,eiin,address,mobile_no,email,locd.name division,LOCZ.NAME zilla,LOCt.NAME upazilla from memis_live.ims_institute JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID and IMS_INSTITUTE.f_ins_type_id=8)
                  LEFT JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) --where f_ins_type_id=10


-----------------------Total no. of Fazil Madrasha from IMS module

select count(*) from ims_institute where f_ins_type_id=9


-----------------------List of Fazil Madrasha from IMS module

select ins_name,eiin,address,mobile_no,email,locd.name division,LOCZ.NAME zilla,LOCt.NAME upazilla from memis_live.ims_institute JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID and IMS_INSTITUTE.f_ins_type_id=9)
                  LEFT JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) --where f_ins_type_id=10



---------------------Total no. of  Kamil Madrasha from IMS module

select count(*) from memis_live.ims_institute where f_ins_type_id=10


--------------------List of Kamil Madrasha from IMS module

select ins_name,eiin,address,mobile_no,email,locd.name division,LOCZ.NAME zilla,LOCt.NAME upazilla from memis_live.ims_institute JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID and IMS_INSTITUTE.f_ins_type_id=10)
                  LEFT JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) --where f_ins_type_id=10


--------------------To find out information about IMS information for a particular division 

 select EIIN,ins_name,locd.name division,LOCZ.NAME zilla,LOCP.NAME paurashava_city,LOCt.NAME,MOBILE_NO,EMAIL upazilla from   memis_live.IMS_INSTITUTE                  
                     JOIN memis_live.SYS_GEO_LOCATION LOC  ON (LOC.GEO_NO  = IMS_INSTITUTE.F_GEO_ID AND IMS_INSTITUTE.MPO_STATUS=1)
                   JOIN memis_live.SYS_GEO_LOCATION LOCD ON ( LOCD.DIVISION = LOC.DIVISION AND LOCD.ZILA = 0 and LOCD.name='DHAKA' )
             JOIN memis_live.SYS_GEO_LOCATION LOCZ ON ( LOCZ.DIVISION = LOC.DIVISION AND LOCZ.ZILA = LOC.ZILA AND LOCZ.NAME='DHAKA' AND LOCZ.UPAZILA_THANA = 0 )
             --LEFT JOIN SYS_GEO_LOCATION LOCU ON ( LOCU.DIVISION = LOC.DIVISION AND LOCU.ZILA = LOC.ZILA AND LOCU.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCU.CITYCORP_PAURASAVA = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCP ON ( LOCP.DIVISION = LOC.DIVISION AND LOCP.ZILA = LOC.ZILA AND  LOCP.UPAZILA_THANA = LOC.UPAZILA_THANA AND  LOCP.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND LOCP.UNION_WARD = 0 )
             LEFT JOIN memis_live.SYS_GEO_LOCATION LOCT ON ( LOCT.DIVISION = LOC.DIVISION AND LOCT.ZILA = LOC.ZILA  AND LOCT.UPAZILA_THANA = LOC.UPAZILA_THANA AND LOCT.CITYCORP_PAURASAVA = LOC.CITYCORP_PAURASAVA AND  LOCT.UNION_WARD = LOC.UNION_WARD) order by division,zilla,paurashava_city
 


